### ISSUE TITLE
Can get the pallet to install

### ISSUE THREAD

**Issue by PondFarmSolar** [krakul/modbus-rtu-slave#5]
ERROR BELOW.... any idears why?-

----------------------------------------------------------
2023-07-18T21:30:14.262Z Install : @krakul/node-red-modbus-rtu-slave 1.0.1

2023-07-18T21:30:14.578Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict @krakul/node-red-modbus-rtu-slave@1.0.1
2023-07-18T21:30:15.685Z [err] npm
2023-07-18T21:30:15.685Z [err]  WARN config production Use `--omit=dev` instead.
2023-07-18T21:30:22.753Z [err] npm
2023-07-18T21:30:22.753Z [err]  ERR! code ENOENT
2023-07-18T21:30:22.753Z [err] npm ERR! syscall spawn git
2023-07-18T21:30:22.753Z [err] npm ERR! path git
2023-07-18T21:30:22.754Z [err] npm ERR!
2023-07-18T21:30:22.754Z [err]  errno -4058
2023-07-18T21:30:22.755Z [err] npm ERR!
2023-07-18T21:30:22.755Z [err]  enoent An unknown git error occurred
2023-07-18T21:30:22.755Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-07-18T21:30:22.755Z [err] npm ERR! enoent 
2023-07-18T21:30:22.756Z [err] 
2023-07-18T21:30:22.756Z [err] npm ERR!
2023-07-18T21:30:22.756Z [err]  A complete log of this run can be found in:
2023-07-18T21:30:22.756Z [err] npm ERR!     C:\Users\kylecarpenter\AppData\Local\npm-cache\_logs\2023-07-18T21_30_15_675Z-debug-0.log
2023-07-18T21:30:22.773Z rc=4294963238

**Comment by sensbo** [comment]
Same issue here, what I tried:

1. install under nodejs v18.18.2; npm 9.81; node-red 3.1.0
2. install under nodejs v20.8.1; npm 10.1.0; node-red 3.1.0

I checked the detail log-files and find this lines in addition to the decribed error from @PondFarmSolar :

```
254 verbose stack Error: An unknown git error occurred
254 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
254 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
254 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
254 verbose stack Error: An unknown git error occurred
254 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
254 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
254 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Any recommandation so far? I assume this node only works for a dedicated nodejs / node-red version, but there is not information available which is required.

**Comment by JaagupAverin** [comment]
Hey! Sorry for the silence - this repository doesn't have anyone from us actively maintaining it.
I can only add for future reference that this package was developed and tested in the following environment:
 - node.js 12.22
 - npm 9.1
 - NodeRED 2.6

**Comment by oktett-8** [comment]
The issue seems to be caused by missing git program. Just make sure git is installed on the system and accessible by Node-RED’s path (as it's the case for an official Node-RED docker container).
Install just works fine using #11 and is tested in the following environment:
 - node.js v20.20.1
 - npm 10.8.2
 - NodeRED v4.1.8
